### ISSUE TITLE
Multipart Uploads for Large Files

### ISSUE THREAD

**Issue by afader** [allenai/datastore#12]
When uploading a large directory of text files (27G uncompressed, 8G compressed), I get an error. I'm guessing we need to use the [S3 MultiPart Upload API](http://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html)?

```
$ java -jar ~/local/bin/DatastoreCLI.jar upload -p pubmed-central/ -g org.allenai.corpora.pubmedcentral -n PubmedCentral -v 1 -d private
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: Your proposed upload exceeds the maximum allowed size (Service: Amazon S3; Status Code: 400; Error Code: EntityTooLarge; Request ID: C538693739F3B6AD), S3 Extended Request ID: hC5wVmtuUfI7LSJHhxoPW8C3REerq1KsdBTrrQ3Ubqn4S2IwbuUbVxamvIS64uq0
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1432)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1289)
	at org.allenai.datastore.Datastore.publish(Datastore.scala:491)
	at org.allenai.datastore.cli.UploadApp$$anonfun$7.apply(UploadApp.scala:52)
	at org.allenai.datastore.cli.UploadApp$$anonfun$7.apply(UploadApp.scala:45)
	at scala.Option.foreach(Option.scala:257)
	at org.allenai.datastore.cli.UploadApp$.delayedEndpoint$org$allenai$datastore$cli$UploadApp$1(UploadApp.scala:45)
	at org.allenai.datastore.cli.UploadApp$delayedInit$body.apply(UploadApp.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.allenai.datastore.cli.UploadApp$.main(UploadApp.scala:7)
	at org.allenai.datastore.cli.DatastoreCli$.delayedEndpoint$org$allenai$datastore$cli$DatastoreCli$1(DatastoreCli.scala:7)
	at org.allenai.datastore.cli.DatastoreCli$delayedInit$body.apply(DatastoreCli.scala:3)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.allenai.datastore.cli.DatastoreCli$.main(DatastoreCli.scala:3)
	at org.allenai.datastore.cli.DatastoreCli.main(DatastoreCli.scala)
```

**Comment by dirkgr** [comment]
Did you get the file uploaded eventually?

**Comment by afader** [comment]
I ended up just not using the datastore on this one---no big deal for now.
