### ISSUE TITLE
Strange behavior on folder upload

### ISSUE THREAD

**Issue by schmmd** [allenai/datastore#15]
```
$ java -jar ~/Downloads/DatastoreCli.jar upload -g "edu.stanford.nlp.models.pos-tagger" --name english-left3words-3.4.1 --version 1
Error: Missing option --path
Try --help for more information.

$ java -jar ~/Downloads/DatastoreCli.jar upload -g "edu.stanford.nlp.models.pos-tagger" --name english-left3words-3.4.1 --version 1 --path .
Exception in thread "main" org.allenai.datastore.Datastore$AlreadyExistsException: edu.stanford.nlp.models.pos-tagger/english-left3words-3.4.1-d1.zip already exists in the public datastore
        at org.allenai.datastore.Datastore.publish(Datastore.scala:459)
        at org.allenai.datastore.cli.UploadApp$$anonfun$7.apply(UploadApp.scala:52)
        at org.allenai.datastore.cli.UploadApp$$anonfun$7.apply(UploadApp.scala:45)
        at scala.Option.foreach(Option.scala:257)
        at org.allenai.datastore.cli.UploadApp$.delayedEndpoint$org$allenai$datastore$cli$UploadApp$1(UploadApp.scala:45)
        at org.allenai.datastore.cli.UploadApp$delayedInit$body.apply(UploadApp.scala:7)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at org.allenai.datastore.cli.UploadApp$.main(UploadApp.scala:7)
        at org.allenai.datastore.cli.DatastoreCli$.delayedEndpoint$org$allenai$datastore$cli$DatastoreCli$1(DatastoreCli.scala:7)
        at org.allenai.datastore.cli.DatastoreCli$delayedInit$body.apply(DatastoreCli.scala:3)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at org.allenai.datastore.cli.DatastoreCli$.main(DatastoreCli.scala:3)
        at org.allenai.datastore.cli.DatastoreCli.main(DatastoreCli.scala)
```

**Comment by schmmd** [comment]
Apparently this was a successful upload.  It would be nice to have a message when the upload starts and when it finishes.  I had to use the CLI to verify that my upload was successful.
